import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Welcome from "./welcome";
import Description from "./description";
import InfoList from "./infoList";
import Graduates from "./graduates";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello turing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/turingLogo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@500;600;700&family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Welcome></Welcome>
      <Description></Description>
      <InfoList></InfoList>
      <Graduates></Graduates>
    </div>
  );
}
